# Generated by Django 4.2.2 on 2023-06-13 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_comment_created_on_alter_post_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 13, 21, 28, 57, 266431)),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 13, 21, 28, 57, 265434)),
        ),
    ]
