# Generated by Django 4.2.2 on 2023-06-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_comment_created_on_alter_post_posted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='images/default-profile-pic.jpg', upload_to='images/'),
        ),
    ]
