# Generated by Django 4.2.2 on 2023-06-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
